[custom]

; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!完整版!!!!!!!!!!!!!!FULL-VER-WITH-ADBLOCKPLUS-AND-ACCURATE-RULES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

; Try this (official) converter if faced with difficulties
; https://sub.xeton.dev/

; mod Xel with love
; @DoingDog

; GeoIP 链接  ;recommended
; Hackl0us GeoIP2-CN https://github.com/Hackl0us/GeoIP2-CN
; 🕔更新频率：每 3 天更新一次
; Country.mmdb（仅中国大陆）
; https://gcore.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb

; alecthw mmdb_china_ip_list https://github.com/alecthw/mmdb_china_ip_list
; 🕔更新频率：每周一
; Country.mmdb（仅中国）
; https://gcore.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/lite/Country.mmdb

; Clash.Easy
; Clash.Easy.yaml

; [ruleset]
; useless?

ruleset=🎯 直连,https://raw.githubusercontent.com/DoingDog/rconvert/main/static/mydirect.txt
ruleset=🎯 直连,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downdr.txt
ruleset=🎯 直连,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downla.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downadvertLi.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downadvertPr.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downadvertZh.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downhj.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/downsukka-reject2.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/SukkaW/Surge/master/List/ip/reject.conf
ruleset=🚧 拦截,https://raw.githubusercontent.com/SukkaW/Surge/master/List/non_ip/reject.conf
ruleset=🚧 拦截,https://raw.githubusercontent.com/SukkaW/Surge/master/List/non_ip/sogouinput.conf
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downwm.txt
ruleset=🚧 拦截,https://raw.githubusercontent.com/DoingDog/rconvert/main/static/clash-misc-rules.list
ruleset=🔍 必应,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downms.txt
ruleset=📺 B站,https://raw.githubusercontent.com/DoingDog/XXKiller/main/myrules/bili.list
ruleset=✈️ 代理,https://raw.githubusercontent.com/DoingDog/rconvert/main/static/qx-proxylist.txt
ruleset=🎯 直连,https://raw.githubusercontent.com/DoingDog/FuckDOMAINSET/main/cv/downcn.txt
ruleset=🎯 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaIPsBGP/ChinaIPsBGP_Resolve.list
ruleset=✈️ 代理,[]FINAL

; [proxy_group]
; 设置分组标志位
; 白名单
; 分你马
; separate your horse
custom_proxy_group=✈️ 代理`select`[]🍥 自动测试`[]♾️ 故障转移`[]👋 手动`[]🇭🇰 自动HK`[]🇨🇳 自动TW`[]🇯🇵 自动JP`[]🇸🇬 自动SG`[]🇺🇸 自动US`[]DIRECT`[]REJECT
custom_proxy_group=👋 手动`select`.*
custom_proxy_group=🔍 必应`select`[]DIRECT`[]REJECT`[]✈️ 代理`[]👋 手动`[]🇭🇰 自动HK`[]🇨🇳 自动TW`[]🇯🇵 自动JP`[]🇸🇬 自动SG`[]🇺🇸 自动US
custom_proxy_group=📺 B站`select`[]DIRECT`[]REJECT`[]✈️ 代理`[]👋 手动`[]🇭🇰 自动HK`[]🇨🇳 自动TW`[]🇯🇵 自动JP`[]🇸🇬 自动SG`[]🇺🇸 自动US
custom_proxy_group=🍥 自动测试`url-test`^[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=♾️ 故障转移`fallback`[]🇭🇰 自动HK`[]🇨🇳 自动TW`[]🇯🇵 自动JP`[]🇸🇬 自动SG`[]🇺🇸 自动US`[]🍥 自动测试`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🇭🇰 自动HK`url-test`^[^戏|易|坡|本|香|巴|美|马|土|俄|酋|荷|门|韩|印|湾|英|法|德|拿|利]*(香港|HK)[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🇨🇳 自动TW`url-test`^[^戏|易|坡|本|香|巴|美|马|土|俄|酋|荷|门|韩|印|湾|英|法|德|拿|利]*(台湾|台灣|臺灣|TW)[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🇯🇵 自动JP`url-test`^[^戏|易|坡|本|香|巴|美|马|土|俄|酋|荷|门|韩|印|湾|英|法|德|拿|利]*(日本|JP)[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🇸🇬 自动SG`url-test`^[^戏|易|坡|本|香|巴|美|马|土|俄|酋|荷|门|韩|印|湾|英|法|德|拿|利]*(新加坡|SG)[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🇺🇸 自动US`url-test`^[^戏|易|坡|本|香|巴|美|马|土|俄|酋|荷|门|韩|印|湾|英|法|德|拿|利]*(美国|美國|US)[^戏|易]*$`http://www.google.com/generate_204`60,1200,200
custom_proxy_group=🎯 直连`select`[]DIRECT`[]✈️ 代理`[]REJECT
custom_proxy_group=🚧 拦截`select`[]REJECT`[]DIRECT`[]✈️ 代理

; useless?
enable_rule_generator=true
overwrite_original_rules=true

; [common]
append_proxy_type=false
; proxy_subscription=SYSTEM
; proxy_ruleset=SYSTEM
proxy_config=SYSTEM
; get out of here (!
clash_rule_base=https://raw.githubusercontent.com/DoingDog/clashconf/main/base.yaml
exclude_remarks=(到期|剩余流量|时间|官网|产品|平台|更新订阅|客服)
; do you play games?
; exclude_remarks=(G-|游戏)

; [node_pref]
; love tls1.3
tls13_flag=true
; no you don't play games
udp_flag=true
; though useless
tcp_fast_open_flag=true
append_sub_userinfo=true
; no
filter_deprecated_nodes=true
; looks better
clash_proxies_style=block
clash_use_new_field_name=true

; [userinfo]
; useless?
stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6

; [managed_config]
config_update_interval = 86400

; [emojis]
; for you
add_emoji=true
remove_old_emoji=true
emoji=(BE |BE-|BE0|BE1|BE2|比利時|比利时),🇧🇪
emoji=(UA |UA-|UA0|UA1|UA2|烏克蘭|乌克兰|基辅),🇺🇦
emoji=(克罗地亚|HR |HR-|HR0|HR1|HR2|克羅地亞),🇭🇷
emoji=(尼日利亚|NG |NG-|NG0|NG1|NG2|尼日利亞|拉各斯),🇳🇬
emoji=(斯洛伐克|SK |SK-|SK0),🇸🇰
emoji=(RS |RS-|RS0|RS1|RS2|塞尔维亚),🇷🇸
emoji=(摩爾多瓦|MD |MD-|MD0|MD1|MD2|摩尔多瓦),🇲🇩
emoji=(DK |DK-|DK0|DK1|DK2|DNK|丹麦|丹麥),🇩🇰
emoji=(ES |ES-|ES0|ES1|ES2|西班牙|Spain),🇪🇸
emoji=(FR |FR-|FR0|FR1|FR2|France|法国|法國|巴黎),🇫🇷
emoji=(UK |GB |UK-|GB-|UK0|GB0|England|United Kingdom|英国|伦敦),🇬🇧
emoji=(MO |MO-|MO0|MO1|MO2|Macao|Macau|MAC|澳门|澳門|CTM),🇲🇴
emoji=(ID |ID-|ID0|ID1|ID2|Indonesia|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(India|IND|INDIA|印度|孟买|Mumbai|IN |IN-|IN0),🇮🇳
emoji=(IS |IS-|IS0|IS1|IS2|ISL|冰岛|冰島),🇮🇸
emoji=(MEX|MX |MX-|MX0|MX1|MX2|墨西哥),🇲🇽️
emoji=(MY |MY-|MY0|MY1|MY2|Malaysia|MALAYSIA|大馬|馬來西亞|吉隆坡|馬來|马来),🇲🇾
emoji=(NL |NL-|NL0|NL1|NL2|Netherlands|荷兰|荷蘭|尼德蘭|阿姆斯特丹),🇳🇱
emoji=(PH |PH-|PH0|PH1|PH2|Philippines|菲律宾|菲律賓),🇵🇭
emoji=(RO |RO-|RO0|RO1|RO2|罗马尼亚),🇷🇴
emoji=(BY |BY-|BY0|BY1|BY2|白俄罗斯|白俄羅斯),🇧🇾
emoji=(KP |朝鲜),🇰🇵
emoji=(SE |SE-|SE0|SE1|SE2|Sweden|瑞典),🇸🇪
emoji=(TH |TH-|TH0|TH1|TH2|Thailand|泰国|泰國|曼谷),🇹🇭
emoji=(TR |TR-|TR0|TR1|TR2|TUR|Turkey|土耳其|伊斯坦布尔),🇹🇷
emoji=(VN |VN-|VN0|VN1|VN2|越南|胡志明市),🇻🇳
emoji=(Italy|IT |IT-|IT0|IT1|IT2|Nachash|意大利|米兰|義大利),🇮🇹
emoji=(United Arab Emirates|阿联酋|AE |AE-|AE0|AE1|AE2|迪拜|Dubai),🇦🇪
emoji=(BR |BR-|BR0|BR1|BR2|Brazil|巴西|圣保罗),🇧🇷
emoji=(AR |AR-|AR0|AR1|AR2|Argentina|阿根廷),🇦🇷
emoji=(Norway|挪威|NO |NO-|NO0),🇳🇴
emoji=(PL |PL-|PL0|PL1|PL2|POL|波兰|波蘭),🇵🇱
emoji=(CY |CY-|CY0|CY1|CY2|塞浦路斯),🇨🇾
emoji=(厄瓜多尔|EC |EC-|EC0),🇪🇨
emoji=(波多黎各|PR |PR-|PR0),🇵🇷
emoji=(黎巴嫩|LB |LB-|LB0),🇱🇧
emoji=(LU |LU-|LU0|LU1|LU2|卢森堡),🇱🇺
emoji=(HU |HU-|HU0|HU1|HU2|匈牙利|Hungary),🇭🇺
emoji=(CH |CH-|CH0|CH1|CH2|瑞士|苏黎世|Switzerland),🇨🇭
emoji=(DE |DE-|DE0|DE1|DE2|German|GERMAN|德国|德國|法兰克福|京德|滬德|廣德|沪德|广德),🇩🇪
emoji=(KR |KR-|KR0|KR1|KR2|Korea|KOR|韩国|首尔|韓|春川),🇰🇷
emoji=(RU |RU-|RU0|RU1|RU2|RUS|Russia|俄罗斯|毛子|俄国|俄羅斯|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|京俄|杭俄|廣俄|滬俄|广俄|沪俄),🇷🇺
emoji=(AU |AU-|AU0|AU1|AU2|Australia|Sydney|澳大利亚|澳洲|墨尔本|悉尼|土澳|京澳|廣澳|滬澳|沪澳|广澳),🇦🇺
emoji=(CA |CA-|CA0|CA1|CA2|Canada|CANADA|CAN|Waterloo|加拿大|蒙特利尔|温哥华|楓葉|枫叶|滑铁卢|多伦多),🇨🇦
emoji=(阿塞拜疆),🇦🇿
emoji=(巴基斯坦),🇵🇰
emoji=(巴林),🇧🇭
emoji=(柬埔寨),🇰🇭
emoji=(奥地利|奧地利|Austria|维也纳),🇦🇹
emoji=(保加利亚|保加利亞|Bulgaria),🇧🇬
emoji=(Czechia|捷克),🇨🇿
emoji=(沙特|利雅得),🇸🇦
emoji=(智利|Chile|CHILE),🇨🇱
emoji=(新西蘭|新西兰),🇳🇿
emoji=(希腊|希臘),🇬🇷
emoji=(埃及),🇪🇬
emoji=(马恩岛|馬恩島),🇮🇲
emoji=(葡萄牙),🇵🇹
emoji=(蒙古),🇲🇳
emoji=(秘鲁|祕魯),🇵🇪
emoji=(哥伦比亚),🇨🇴
emoji=(爱沙尼亚),🇪🇪
emoji=(马其顿|馬其頓),🇲🇰
emoji=(马耳他),🇲🇹
emoji=(委内瑞拉),🇻🇪
emoji=(波黑共和国|波黑),🇧🇦
emoji=(格魯吉亞|格鲁吉亚),🇬🇪
emoji=(阿爾巴尼亞|阿尔巴尼亚),🇦🇱
emoji=(哥斯达黎加),🇨🇷
emoji=(突尼斯),🇹🇳
emoji=(巴拿马|巴拿馬),🇵🇦
emoji=(伊朗),🇮🇷
emoji=(约旦),🇯🇴
emoji=(乌拉圭),🇺🇾
emoji=(肯尼亚),🇰🇪
emoji=(吉尔吉斯坦|吉尔吉斯斯坦),🇰🇬
emoji=(尼泊尔),🇳🇵
emoji=(科索沃),🇽🇰
emoji=(摩洛哥),🇲🇦
emoji=(安道尔),🇦🇩
emoji=(巴拉圭),🇵🇾
emoji=(亚美尼亚),🇦🇲
emoji=(留尼汪),🇷🇪
emoji=(Israel|以色列),🇮🇱
emoji=(Latvia|Latvija|拉脱维亚),🇱🇻
emoji=(孟加拉),🇧🇩
emoji=(South Africa|南非|Johannesburg),🇿🇦
emoji=(Finland|芬兰|芬蘭|赫尔辛基),🇫🇮
emoji=(哈萨克斯坦),🇰🇿
emoji=(斯洛文尼亚),🇸🇮
emoji=(立陶宛),🇱🇹
emoji=(斯里兰卡),🇱🇰
emoji=(Ireland|IRELAND|爱尔兰|愛爾蘭|都柏林),🇮🇪
emoji=(US|USA|America|United States|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|矽谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美|哥伦布|纽约),🇺🇸
emoji=(TW|Taiwan|TAIWAN|台湾|台北|台中|新北|彰化|CHT|台|HINET),🇹🇼
emoji=(SG|SG-|Singapore|SINGAPORE|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新|广新|廣新|滬新),🇸🇬
emoji=(JP|JP-|Japan|JAPAN|日本|东京|大阪|埼玉|穗日|川日|中日|泉日|杭日|深日|辽日|广日),🇯🇵
emoji=(HK|Hongkong|Hong Kong|HongKong|HONG KONG|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港),🇭🇰
emoji=(流量|套餐|剩余|重置|到期|时间|应急|过期|Bandwidth|expire|Expire|reset|Reset|traffic|Traffic),🏳️‍🌈
emoji=(CN|CN-|China|回国|中国|中國|江苏|北京|上海|广州|深圳|杭州|徐州|青岛|宁波|镇江|back),🇨🇳
emoji=(EU|EU-|欧盟|欧罗巴|欧洲),🇪🇺
emoji=(亚洲),🌏
emoji=(流媒体|Netflix|NETFLIX|NF|视频|解锁),📺
emoji=(DL|下载|大流量|大数据),⚡️
emoji=(GA|游戏),🎮
emoji=(.*),🏴‍☠️

; [advanced]
; better than fail
skip_failed_links=true

; modify as you like
; luck
