#  已经过特殊设置 可以用于路由器
#  yacd.haishan.me ip:9090 打开控制面板
#  太复杂了
#  没有ipv6
#  @DoingDog

#port: 7889
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
routing-mark: 6666
geodata-mode: false
unified-delay: true
udp: true
enable-process: true
geox-url:
  mmdb: "https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.mmdb"
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat"
  geosite: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat"
iptables:
  enable: true
log-level: info
profile:
  store-selected: true
  store-fake-ip: true
  tracing: false
ipv6: false
external-controller: 0.0.0.0:9090
secret: ""
experimental:
  ignore-resolve-fail: true
hosts:
  'localhost': 127.0.0.1
ebpf:
  redirect-to-tun: ~
sniffer:
   enable: true
   sniffing:
     - tls
     - http
   port-whitelist:
     - 80
     - 443
     - 8000-9000
   skip-domain:
     - 'Mijia Cloud'
     - '+.apple.com'
   force-domain:
     - www.google.com
tcp-concurrent: true
clash-for-android:
  append-system-dns: false
dns:
  enable: true
  ipv6: false
  use-hosts: true
  listen: 0.0.0.0:3553
  enhanced-mode: fake-ip #redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - '*.*.xboxlive.com'
    - '*.126.net'
    - '*.blzstatic.cn'
    - '*.cmbchina.com'
    - '*.cmpassport.com'
    - '*.icitymobile.mobi'
    - '*.jegotrip.com.cn'
    - '*.kuwo.cn'
    - '*.lan'
    - '*.logon.battle.net'
    - '*.logon.battlenet.com.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.music.163.com'
    - '*.music.migu.cn'
    - '*.ntp.org.cn'
    - '*.pingan.com.cn'
    - '*.pool.ntp.org'
    - '*.xiami.com'
    - '*.y.qq.com'
    - '+.detectportal.firefox.com'
    - '+.network-test.debian.org'
    - '+.resolver1.opendns.com'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
    - 'PDC._msDCS.*.*'
    - 'amobile.music.tc.qq.com'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'aqqmusic.tc.qq.com'
    - 'auth.wosms.cn'
    - 'cable.auth.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'id6.me'
    - 'isure.stream.qqmusic.qq.com'
    - 'joox.com'
    - 'localhost.ptlogin2.qq.com'
    - 'mdn.open.wo.cn'
    - 'mobileoc.music.tc.qq.com'
    - 'music.163.com'
    - 'music.migu.cn'
    - 'music.taihe.com'
    - 'musicapi.taihe.com'
    - 'ntp.*.com'
    - 'ntp?.*.com'
    - 'open.e.189.cn'
    - 'pool.ntp.org'
    - 'proxy.golang.org'
    - 'songsearch.kugou.com'
    - 'streamoc.music.tc.qq.com'
    - 'stun.*'
    - 'time.*.com'
    - 'time.*.edu.cn'
    - 'time.*.gov'
    - 'time?.*.com'
    - 'trackercdn.kugou.com'
    - 'xbox.*.*.microsoft.com'
    - 'y.qq.com'
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
  nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 120.53.53.78
    - 120.53.53.12
  proxy-server-nameserver:
    - 101.42.236.152:777
    - 81.70.168.21:777
    - 113.125.128.91:777
    - 124.225.182.156:777
    - 42.194.141.208:777
    - 61.171.81.150:777
  nameserver-policy:
    '+.1688.com': '223.5.5.5'
    '+.aliapp.com': '223.5.5.5'
    '+.aliapp.org': '223.5.5.5'
    '+.alibaba.cn': '223.5.5.5'
    '+.alibaba.com.cn': '223.5.5.5'
    '+.alibabausercontent.com': '223.5.5.5'
    '+.alicdn.com': '223.5.5.5'
    '+.alipay-eco.com': '223.5.5.5'
    '+.alipay.com': '223.5.5.5'
    '+.alipay.com.cn': '223.5.5.5'
    '+.alipaydns.com': '223.5.5.5'
    '+.alipayeshop.com': '223.5.5.5'
    '+.alipaylog.com': '223.5.5.5'
    '+.alipayobjects.com': '223.5.5.5'
    '+.aliyun.*': '223.5.5.5'
    '+.aliyuncdn.*': '223.5.5.5'
    '+.aliyuncs.com': '223.5.5.5'
    '+.aliyunddos*.com': '223.5.5.5'
    '+.aliyundrive.com': '223.5.5.5'
    '+.aliyundunwaf.com': '223.5.5.5'
    '+.china.alibaba.com': '223.5.5.5'
    '+.mmstat.com': '223.5.5.5'
    '+.taobao.com': '223.5.5.5'
    '+.tbcache.com': '223.5.5.5'
    '+.tmall.com': '223.5.5.5'
    '+.cdn-go.cn': '119.29.29.29'
    '+.gtimg.cn': '119.29.29.29'
    '+.idqqimg.com': '119.29.29.29'
    '+.myqcloud.com': '119.29.29.29'
    '+.qcloud.com': '119.29.29.29'
    '+.qcloudcdn.cn': '119.29.29.29'
    '+.qcloudcdn.com': '119.29.29.29'
    '+.qcloudcjgj.com': '119.29.29.29'
    '+.qcloudcos.com': '119.29.29.29'
    '+.qcloudimg.com': '119.29.29.29'
    '+.qcloudwzgj.com': '119.29.29.29'
    '+.qcloudzygj.com': '119.29.29.29'
    '+.qlogo.cn': '119.29.29.29'
    '+.qpic.cn': '119.29.29.29'
    '+.qq.com': '119.29.29.29'
    '+.servicewechat.com': '119.29.29.29'
    '+.smtcdns.com': '119.29.29.29'
    '+.smtcdns.net': '119.29.29.29'
    '+.tencent-cloud.net': '119.29.29.29'
    '+.tencent.com': '119.29.29.29'
    '+.tencentcloud-aiot.com': '119.29.29.29'
    '+.tencentcloudapi.com': '119.29.29.29'
    '+.tencentcloudcr.com': '119.29.29.29'
    '+.tencentcloudmarket.com': '119.29.29.29'
    '+.wechat.com': '119.29.29.29'
    '+.weixin.com': '119.29.29.29'
    '+.weixin.qq.com': '119.29.29.29'
    '+.weixinbridge.com': '119.29.29.29'
    '+.weiyun.com': '119.29.29.29'
    '+.wx.qq.com': '119.29.29.29'
    '+.*-apple.*': '223.5.5.5'
    '+.*-apple.*.*': '223.5.5.5'
    '+.aaplimg.*': '223.5.5.5'
    '+.aaplimg.*.*': '223.5.5.5'
    '+.apple': '223.5.5.5'
    '+.apple-*': '223.5.5.5'
    '+.apple-*.*': '223.5.5.5'
    '+.apple.*': '223.5.5.5'
    '+.apple.*.*': '223.5.5.5'
    '+.icloud.*': '223.5.5.5'
    '+.icloud.*.*': '223.5.5.5'
    '+.mzstatic.*': '223.5.5.5'
    '+.mzstatic.*.*': '223.5.5.5'
  fallback:
    - 101.42.236.152:777
    - 81.70.168.21:777
    - 113.125.128.91:777
    - 124.225.182.156:777
    - 42.194.141.208:777
    - 61.171.81.150:777
  fallback-filter:
    geoip: false
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.0/8
      - 0.0.0.0/8
      - 100.64.0.0/10
      - 169.254.0.0/16
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.google.cn'
      - '+.googleapis.cn'
      - '+.translate.googleapis.com'
      - '+.safebrowsing.googleapis.com'
      - '+.clientservices.googleapis.com'
      - '+.bing.com'
      - '+.linkedin.com'
      - '+.msn.cn'
      - '+.playstationnetwork.com'
      - '+.sony.com'
      - '+.sonyentertainmentnetwork.com'
      - '+.playstation.com'
      - '.ac'
      - '.ad'
      - '.ae'
      - '.aero'
      - '.af'
      - '.ag'
      - '.ai'
      - '.al'
      - '.am'
      - '.ao'
      - '.app'
      - '.aq'
      - '.ar'
      - '.art'
      - '.as'
      - '.asia'
      - '.at'
      - '.au'
      - '.aw'
      - '.ax'
      - '.az'
      - '.ba'
      - '.bar'
      - '.bb'
      - '.bd'
      - '.be'
      - '.beauty'
      - '.best'
      - '.bf'
      - '.bg'
      - '.bh'
      - '.bi'
      - '.bible'
      - '.biz'
      - '.bj'
      - '.bm'
      - '.bn'
      - '.bo'
      - '.br'
      - '.bs'
      - '.bt'
      - '.buzz'
      - '.bw'
      - '.by'
      - '.bz'
      - '.ca'
      - '.cat'
      - '.catholic'
      - '.cd'
      - '.cf'
      - '.cg'
      - '.ch'
      - '.chat'
      - '.church'
      - '.ci'
      - '.ck'
      - '.cl'
      - '.cloud'
      - '.club'
      - '.cm'
      - '.co'
      - '.college'
      - '.company'
      - '.cool'
      - '.coop'
      - '.cr'
      - '.cu'
      - '.cv'
      - '.cw'
      - '.cx'
      - '.cy'
      - '.cyou'
      - '.cz'
      - '.day'
      - '.de'
      - '.design'
      - '.dev'
      - '.digital'
      - '.dj'
      - '.dk'
      - '.dm'
      - '.do'
      - '.dog'
      - '.download'
      - '.dz'
      - '.earth'
      - '.ec'
      - '.eco'
      - '.edu'
      - '.ee'
      - '.eg'
      - '.er'
      - '.es'
      - '.et'
      - '.eu'
      - '.eu.org'
      - '.fi'
      - '.fit'
      - '.fj'
      - '.fk'
      - '.fm'
      - '.fo'
      - '.fr'
      - '.fun'
      - '.fyi'
      - '.ga'
      - '.game'
      - '.gay'
      - '.gd'
      - '.ge'
      - '.gf'
      - '.gg'
      - '.gh'
      - '.gi'
      - '.gl'
      - '.glass'
      - '.global'
      - '.gm'
      - '.gn'
      - '.google'
      - '.gov'
      - '.gp'
      - '.gq'
      - '.gr'
      - '.green'
      - '.gs'
      - '.gt'
      - '.gu'
      - '.gw'
      - '.gy'
      - '.health'
      - '.hk'
      - '.hm'
      - '.hn'
      - '.homes'
      - '.host'
      - '.hr'
      - '.ht'
      - '.hu'
      - '.icu'
      - '.id'
      - '.ie'
      - '.il'
      - '.im'
      - '.in'
      - '.inc'
      - '.info'
      - '.ink'
      - '.int'
      - '.iq'
      - '.ir'
      - '.is'
      - '.it'
      - '.je'
      - '.jm'
      - '.jo'
      - '.jobs'
      - '.jp'
      - '.ke'
      - '.kg'
      - '.kh'
      - '.ki'
      - '.kid'
      - '.km'
      - '.kn'
      - '.kp'
      - '.kr'
      - '.kw'
      - '.ky'
      - '.kz'
      - '.la'
      - '.lb'
      - '.lc'
      - '.li'
      - '.life'
      - '.link'
      - '.live'
      - '.lk'
      - '.loan'
      - '.lol'
      - '.love'
      - '.lr'
      - '.ls'
      - '.lt'
      - '.lu'
      - '.lv'
      - '.ly'
      - '.ma'
      - '.mc'
      - '.md'
      - '.me'
      - '.media'
      - '.men'
      - '.mg'
      - '.mh'
      - '.mil'
      - '.mk'
      - '.ml'
      - '.mm'
      - '.mn'
      - '.mo'
      - '.mobi'
      - '.moe'
      - '.monster'
      - '.mp'
      - '.mq'
      - '.mr'
      - '.ms'
      - '.mt'
      - '.mu'
      - '.museum'
      - '.mv'
      - '.mw'
      - '.mx'
      - '.my'
      - '.mz'
      - '.na'
      - '.name'
      - '.nc'
      - '.ne'
      - '.network'
      - '.nf'
      - '.ng'
      - '.ni'
      - '.nl'
      - '.no'
      - '.np'
      - '.nr'
      - '.nu'
      - '.nz'
      - '.om'
      - '.one'
      - '.online'
      - '.ooo'
      - '.pa'
      - '.pe'
      - '.pf'
      - '.pg'
      - '.ph'
      - '.pics'
      - '.pk'
      - '.pl'
      - '.pm'
      - '.pn'
      - '.post'
      - '.pr'
      - '.pro'
      - '.ps'
      - '.pt'
      - '.pub'
      - '.pw'
      - '.py'
      - '.qa'
      - '.quest'
      - '.re'
      - '.rest'
      - '.rip'
      - '.ro'
      - '.rocks'
      - '.rs'
      - '.ru'
      - '.run'
      - '.rw'
      - '.sa'
      - '.sb'
      - '.sbs'
      - '.sc'
      - '.sd'
      - '.se'
      - '.sex'
      - '.sg'
      - '.sh'
      - '.shop'
      - '.si'
      - '.site'
      - '.sk'
      - '.sl'
      - '.sm'
      - '.sn'
      - '.so'
      - '.space'
      - '.sr'
      - '.ss'
      - '.st'
      - '.store'
      - '.su'
      - '.sv'
      - '.sx'
      - '.sy'
      - '.sz'
      - '.tc'
      - '.td'
      - '.team'
      - '.tech'
      - '.tel'
      - '.tf'
      - '.tg'
      - '.th'
      - '.tj'
      - '.tk'
      - '.tl'
      - '.tm'
      - '.tn'
      - '.to'
      - '.today'
      - '.tokyo'
      - '.top'
      - '.tr'
      - '.travel'
      - '.tt'
      - '.tv'
      - '.tw'
      - '.tz'
      - '.ua'
      - '.ug'
      - '.uk'
      - '.uno'
      - '.us'
      - '.uy'
      - '.uz'
      - '.va'
      - '.vc'
      - '.ve'
      - '.vg'
      - '.vi'
      - '.video'
      - '.vip'
      - '.vn'
      - '.vu'
      - '.website'
      - '.wf'
      - '.wiki'
      - '.win'
      - '.work'
      - '.ws'
      - '.wtf'
      - '.xxx'
      - '.xyz'
      - '.ye'
      - '.yt'
      - '.za'
      - '.zm'
      - '.zone'
      - '.zw'
tun:
  enable: false
  device: meta
  stack: gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - 0.0.0.0:53
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
cfw-latency-timeout: 1200
cfw-latency-url: http://www.google.com/generate_204
cfw-conn-break-strategy:
  proxy: chain
  profile: true
  mode: true
cfw-proxies-order: default
cfw-bypass:
  - "localhost"
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
